### ISSUE TITLE
Users always offline

### ISSUE THREAD

**Issue by Ma-Altaiir** [mesibo/samples#1]
Hello;

I tried code  samples, created users from dashboard and used access tokens from there, tried to send messages but nothing happening.
Would you please clarify what return values are used for functions like mesibo.start() , sendMessage() and so on ... and , is there any additional step to go for after initializing mesibo and calling start(), user should be online after start() called and succeded (i get 0 as result).

**Comment by mesibo** [comment]
Have you implemented connection listener? Does 
mesibo_onConnectionStatuA gets called after you invoke start ()

If you are developing on Android, ensure that network permission is given. Kindly look at sample application for required permissions. 

If you still having issues, please post your code.

**Comment by Ma-Altaiir** [comment]
I got this now , the issue was my misunderstanding of documentation and bad implemebtation, i am trying now to get a two way messaging.
Thank you
