### ISSUE TITLE
Support level

### ISSUE THREAD

**Issue by vinay1991** [mesibo/samples#10]
Hi Team,

Just wanted to check with you that how fast you can reply we will use this SDK for our application as we are in hurry and want to deliver by November.

How can we connect so that support communication can be fast. We can't wait 1-2 days for reply while development. Please let us know best way of communication with you. Thanks!

**Comment by mesibo** [comment]
Kindly email us your detailed requirements and any questions you may have from our contact page. We will swiftly revert. 

Also, have you tried our demo apps? Our demo apps are available on both Google and Apple play store. You can install it on your phones and try mesibo features. 

https://itunes.apple.com/us/app/mesibo-realtime-messaging-voice-video/id1222921751
https://play.google.com/store/apps/details?id=com.mesibo.mesiboapplication

**Comment by vinay1991** [comment]
Yes we have tried the demo for Mobile. But we wanted the same functionalities in web application as well but we didn't find any sample for the same.
