### ISSUE TITLE
Login API not working in Sample App 

### ISSUE THREAD

**Issue by techradiusopc** [mesibo/samples#18]
Hello Team 

https://api.mesibo.com/api.php

INPUT TYPE: POST 

Input Parameter/Request: 
{"op":"login","name":"TechRadius","phone":"91********25","aid":"com.mesibo.firstsample","ns":"aXmsal0q7nNNy"}

response is

{"op":"login","result":false,"error":"MISSINGPARA"}

Note: 1. please explain to me ns(namespace) how we create it?
2. I found doc from here https://github.com/mesibo/messenger-app-backend/blob/master/api.php

**Comment by mesibo** [comment]
Pls do not raise duplicate support request on email and here.
