### ISSUE TITLE
undefined is not an object (evaluating '_MesiboModule2.default.init')

### ISSUE THREAD

**Issue by vkkan** [mesibo/samples#22]
Hello,

I have downloaded and installed npm dependencies and running project via xcode that time I am getting given below error

undefined is not an object (evaluating '_MesiboModule2.default.init')

Pls help me out

**Comment by mesibo** [comment]
You appear to be using android react-native sample code on Xcode. You need to change sample code using Mesibo iOS sdk.

**Comment by vkkan** [comment]
Here is what I am doing .

We are building app using react native , would like to add chat into the app so we have downloaded the samples and running react native app from the sample of this repo i.e https://github.com/mesibo/samples/tree/master/react-native/helloworld

We tried running on android and getting bug zero uid error on Mac we are getting the error undefined is not an object (evaluating '_MesiboModule2.default.init') 

Pls tell me whether you guys support react native or not if yes pls share the working sample or how to do

**Comment by gandol** [comment]
any idea to solve this issue ?

**Comment by hackrx** [comment]
@mesibo This is the same error I am getting, limiting conversation to only collaborators does not work for open source code, please provide a solution for this, or else don't say that you are supporting `react-native`
You may also look at this [StackOverflow](https://stackoverflow.com/questions/60850746/how-do-i-receive-real-time-messages-in-react-native-from-mesibo) question
#39 
@vkkan, @gandol  did you found any solution for this?

**Comment by mesibo** [comment]
Refer https://mesibo.com/documentation/faq/#does-mesibo-supports-cross-platform-tools-like-flutter-react-native-ionic-etc

**Comment by mesibo** [comment]
We have updated the repository with a react-native sample to send messages and make video and voice calls. 

A sample project is available for Android which you can build and run. You can follow similar steps to use Mesibo with React Native in iOS by creating a [Native Module in iOS](https://reactnative.dev/docs/native-modules-ios).
