### ISSUE TITLE
Incomplete Sample

### ISSUE THREAD

**Issue by StartappzKE** [mesibo/samples#3]
Missing Classes
1. LayoutMessageShowBinding
2. DataBindingUtil

Or incomplete android sample

**Comment by StartappzKE** [comment]
Here is the complete logs

Information:Gradle tasks [clean, :app:assembleDebug]
/Users/startappz/Documents/AndroidStudioProjects/WyAds/app/src/main/java/ads/wyzone/com/wyads/mesibo/SampleAppWebApi.java
Error:(63, 38) error: cannot find symbol method getContext()
Error:(67, 27) error: cannot find symbol method startMesibo()
Error:(83, 43) error: cannot find symbol method getContext()
Error:(113, 35) error: cannot find symbol method startMesibo()
/Users/startappz/Documents/AndroidStudioProjects/WyAds/app/src/main/java/ads/wyzone/com/wyads/DemoActivity.java
Error:(3, 27) error: package android.databinding does not exist
Error:(26, 13) error: cannot find symbol class ActivityDemoBinding
Error:(42, 20) error: cannot find symbol variable DataBindingUtil
/Users/startappz/Documents/AndroidStudioProjects/WyAds/app/src/main/java/ads/wyzone/com/wyads/adapters/DemoActivityMessageAdapter.java
Error:(46, 16) error: cannot find symbol class LayoutMessageShowBinding
Error:(47, 27) error: cannot find symbol class LayoutMessageShowBinding
Error:(25, 9) error: cannot find symbol class LayoutMessageShowBinding
Error:(25, 45) error: cannot find symbol variable LayoutMessageShowBinding
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED in 1m 35s
Information:12 errors
Information:0 warnings
Information:See complete output in console

**Comment by mesibo** [comment]
As I can see from the logs, you have customized path etc (Users/startappz/Documents/AndroidStudioProjects/WyAds/app/src/main/java/ads/wyzone/com/wyads) and we can't provide support on your custom projects. 

Please use sample as it is which is compiling fine. Feel free to reopen if you having the issue with unmodified code.
