### ISSUE TITLE
Reply design issue

### ISSUE THREAD

**Issue by Chinnam365** [mesibo/samples#45]
The reply chat design has an issue. When a user replies to a comment on chat it is clearly shown on the sender side and no issues here. The receiver doesn't see it as a reply comment but rather receiver see it as another comment. Can you fix it

**Comment by mesibo** [comment]
At the sender side, you get `refid` which should be used to show the reply UI. The source code for UI is available here which you can modify https://github.com/mesibo/ui-modules-android

We have to plan to update UI source code in July 2020, after the conference release which is shortly planned.
