### ISSUE TITLE
Mesibo integration with IONIC

### ISSUE THREAD

**Issue by ladaniavadh** [mesibo/samples#47]
Hello,
I would like to integrate the mesibo in my IONIC-4 app, I tried to find the documentation or tutorial for the same but not able to find anything.

Now I am thinking implement in this way: create APIs using Backend code with different endpoints and implement the APIs in my IONIC app. (But backend code is in CORE PHP so i think this will tough to integrate with framework)

Please let me know if you have any other possible way to implement

**Comment by mesibo** [comment]
PHP code is just the sample. Use mesibo REST API to create endpoints. Read documentation.
