### ISSUE TITLE
I am unable to run project just after installing the Mesibo throw cocapod in Xcode 11.2

### ISSUE THREAD

**Issue by vijaypatidar2102** [mesibo/samples#49]
pod 'mesibo' ,pod 'mesibo-ui' , pod 'mesibo-calls'. I have use this pods.

Undefined symbol: _OBJC_CLASS_$_RTCDispatcher
Undefined symbol: _OBJC_CLASS_$_RTCCameraVideoCapturer

Showing Recent Messages
Undefined symbol: _query_mesibo_webrtc

Undefined symbol: _OBJC_CLASS_$_RTCIceServer

Undefined symbol: _OBJC_CLASS_$_RTCIceCandidate

Undefined symbol: _OBJC_CLASS_$_RTCConfiguration

Undefined symbol: _OBJC_CLASS_$_RTCMediaConstraints

Undefined symbol: _RTCLogEx

Undefined symbol: _OBJC_CLASS_$_RTCAudioSession

Undefined symbol: _OBJC_CLASS_$_RTCFileVideoCapturer

Undefined symbol: _OBJC_CLASS_$_RTCSessionDescription

Undefined symbol: ___darwin_check_fd_set_overflow

Undefined symbol: _OBJC_CLASS_$_RTCPeerConnectionFactory

Undefined symbol: _RTCFileName

Undefined symbol: _OBJC_CLASS_$_RTCEAGLVideoView

**Comment by mesibo** [comment]
https://mesibo.com/documentation/faq/demo-apps/#how-to-resolve-ios-linker-errors-in-the-demo-app
