### ISSUE TITLE
Getting error after adding required frameworks for mesibo chat lib

### ISSUE THREAD

**Issue by PramodShukla10** [mesibo/samples#5]
duplicate symbol _kReachabilityChangedNotification in:
    /Users/rudimentwebtech/Library/Developer/Xcode/DerivedData/LetsShoot-csdtaecfiimzadftmwedowfxzxpk/Build/Products/Debug-iphonesimulator/Reachability/libReachability.a(Reachability.o)
projectpath/mesibo.framework/mesibo(libsom_mesibo_x86_64.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mesibo** [comment]
Earlier version had a symbol conflict with reachability library. Remove reachability library from your project or use latest mesibo-framework 1.0.4 that has fixed this issue.
