### ISSUE TITLE
Android Login Button Press issue

### ISSUE THREAD

**Issue by DimplePanesara** [mesibo/samples#51]
Login button press time stuck in process. Not open next screen. 
Log debug:
ssistStructure: Flattened final assist data: 2684 bytes, containing 1 windows, 9 views
I/MesiboJNI: E(1207-002939-038)(26822): starting ssl
I/MesiboJNI: E(1207-002939-545)(26822): handshake completed in 505916
I/MesiboJNI: E(1207-002951-832)(26847): starting ssl
I/MesiboJNI: E(1207-002952-587)(26847): handshake completed in 755118
I/MesiboJNI: E(1207-003002-434)(26861): starting ssl
I/MesiboJNI: E(1207-003002-990)(26861): handshake completed in 556108

**Comment by mesibo** [comment]
Read documentation and tutorials https://mesibo.com/documentation/tutorials/first-app/
