### ISSUE TITLE
Mesibo JS for web shut down after 5 sec and never turn on remote video

### ISSUE THREAD

**Issue by sakihayashi** [mesibo/samples#60]
As instructed, I created two users and changed the user tokens and the app id.

I hosted two websites(each website hardcoded a unique user token I created from Mesibo online and use the same user app id + call destination each other ) via https and tested.

The result is:

1. it was able to call another user I set and was able to answer the call between the two users.
2. The call is answered but never turned on the remote video and voice. I see the local video only.
3. it automatically shut down after about 5 sec.

The status of Mesibo UI has a record of calling. 99 messages sent today and the bandwidth is 65.27 K.

Does anyone know how to solve this?

**Comment by conrad93** [comment]
@sakihayashi hey i am facing the same issue did u get any solution???

**Comment by mesibo** [comment]
1) are you able to exchange messages. If so, calls should work.
2) You MUST use a secure URL. Calls will not work on HTTP.

If that's not the case, host your code somewhere and share the secure URL. We will help you.
