### ISSUE TITLE
Error UnsatisfiedLinkError on Release variant

### ISSUE THREAD

**Issue by adisiji** [mesibo/samples#65]
I got this error when build for release variant:

Process: id.co.yy.xx.dev.debug, PID: 30114
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mesibo.api.JNIAPI.set_security(int) (tried Java_com_mesibo_api_JNIAPI_set_1security and Java_com_mesibo_api_JNIAPI_set_1security__I)
        at com.mesibo.api.JNIAPI.set_security(Native Method)
        at com.mesibo.api.Mesibo.setSecureConnection(SourceFile:2)

My Config:
BUILD_TOOLS_VERSION = "29.0.2"
COMPILE_SDK_VERSION = 30
MIN_SDK_VERSION = 21
TARGET_SDK_VERSION = 30

Mesibo version I use:
MESIBO_CALLS = "1.2.90"
MESIBO_API = "1.2.89"
MESIBO_UI = "1.2.89"

Hope you can help me quickly !
Thank you!

**Comment by mesibo** [comment]
Make sure that your proguard does not remove mesibo classes

```
-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

-keep class com.mesibo.** { *; }
```

**Comment by adisiji** [comment]
Ok. Thanks!
