### ISSUE TITLE
Error SQL at Start Mesibo 

### ISSUE THREAD

**Issue by adisiji** [mesibo/samples#69]
I got this error when starting Mesibo. Then the app become not responding.
Error Log:
```
I/MesiboJNI: E(2307-084947-562)(8014): jlogs: Mesibo API Version: 1.5.5
I/MesiboJNI: E(2307-085002-456)(8014): SQL Error: update messages set status=132 where  status=0 AND (flag&2097152)=0 AND (ts + (expiry*1000)) < 1627005004456
I/MesiboJNI: E(2307-085002-457)(8014): SQL Error: delete from messages where channel in (129, 130) and status >= 1
I/MesiboJNI: E(2307-085002-457)(8014): SQL Error: delete from messages where rts > 0 and status!=0 and rts < 1627005002457
I/MesiboJNI: E(2307-085002-485)(8873): readContact: failed
V/FA-SVC: Logging event: origin=app,name=select_item,params=Bundle[{item_name=true, ga_event_origin(_o)=app, ga_screen_class(_sc)=MesiboToggleFragment, ga_screen_id(_si)=-79151485638078673, ga_screen(_sn)=Mesibo Toggle, items=activate_mesibo, item_id=}]
I/MesiboJNI: E(2307-085002-783)(8874): *** BUG *** openssl session management not implemented
I/MesiboJNI: E(2307-085003-432)(8874): handshake completed in 648747
I/MesiboJNI: E(2307-085003-522)(8874): SQL Error: delete from messages where gid=0 and sender='' and (status=18 or status=19);
```

Please Help. 
Thank You in Advance!

**Comment by mesibo** [comment]
@adisiji have you initialized the app with the right tokens as explained here 

https://mesibo.com/documentation/tutorials/get-started/

**Comment by adisiji** [comment]
Yes, I have set up as in the example.
The problem is here : `Mesibo.setDatabase("mesibo-custom.db", 1)`
If I set the reset as `1` it will crash, but if `0` it will succeed. 
But I need to reset the database if the user is logout from the App.

**Comment by mesibo** [comment]
Do not reset it, each user has its own database. Refer to the API description here

https://mesibo.com/documentation/api/real-time-api/initialization/#setdatabase

**Comment by mesibo** [comment]
Do not send issues without technical details and code. Do not use old threads.
