### ISSUE TITLE
Set Image URL

### ISSUE THREAD

**Issue by adisiji** [mesibo/samples#70]
I'm trying to set the imageUrl of MesiboProfile

Code:
```
val mesiboProfile = Mesibo.getProfile(profileId)
mesiboProfile.imageUrl = "https://pathtoimage.jpg"
mesiboProfile.save()
```

But when I try to get the profile again, it return the `imageUrl` is `null`
How is this possible? 

Android SDK Mesibo Version:
- MESIBO_API = "1.5.5"
- MESIBO_CALLS = "1.5.2"
- MESIBO_UI = "1.5.2"

Thank You

**Comment by mesibo** [comment]
Read "Before you send us a Support Request" section here https://mesibo.com/support/

**Comment by adisiji** [comment]
Updated

**Comment by mesibo** [comment]
I tried the below code with latest API (1.6.4) and it worked as expected. Ensure that your database is set. 

```
MesiboProfile g = Mesibo.getProfile(profileId);
g.setImageUrl("https://pathtoimage.jpg");
g.save();
String imageUrl = g.getImageUrl();
```

Also, it is generally recommended to use a self profile to set any properties and not to modify the profile returned by the getProfile. Read profile documentation.

**Comment by adisiji** [comment]
Ok. I've updated the SDK to latest API (1.6.4)

If I set the imageUrl and then get imageUrl, it is not null. But when I get the imageUrl from the other device, the imageUrl is null.
I also have setup the database as below:
```
        val mesiboToken = tokenRepository.loadMesiboToken()
        val setAccessToken = Mesibo.setAccessToken(mesiboToken)
        Timber.d("SetAccessToken Mesibo : $setAccessToken")

        val setDatabase = Mesibo.setDatabase("mesibo.db", 0)
        Timber.d("SetDB Mesibo : $setDatabase")

        // Now start mesibo
        val startMesibo = Mesibo.start()
        Timber.d("Start Mesibo : $startMesibo")
```

**Comment by mesibo** [comment]
Did you read my comment? YOU MUST publish your self profile to read from another device.

Read documentation. closing ticket.
