### ISSUE TITLE
Failure Set ImageURL Mesibo Profile

### ISSUE THREAD

**Issue by adisiji** [mesibo/samples#71]
I'm trying to set the imageUrl of MesiboProfile

Code:
```
val mesiboProfile = Mesibo.getProfile(profileId)
mesiboProfile.imageUrl = "https://pathtoimage.jpg"
mesiboProfile.save()
```

But when I try to get the profile again, it return the imageUrl is null
How is this possible?

Android SDK Mesibo Version:

- MESIBO_API = "1.5.5"
- MESIBO_CALLS = "1.5.2"
- MESIBO_UI = "1.5.2"

Thank You

**Comment by mesibo** [comment]
Duplicate! answered in another thread.
