### ISSUE TITLE
"createGroup" method creates duplicate group on invoke (Javascript)

### ISSUE THREAD

**Issue by vyonizr** [mesibo/samples#73]
Platform: Javascript
Build date: Sep 26, 2021 12:31 GMT

I implement `createGroup` method as documented on https://mesibo.com/documentation/api/real-time-api/groups/ .

My code snippet:
```javascript
 MesiboApi.createGroup(groupName.msg, 0, function (createdGroup) {
    const groupPermissions = {
      flags: 0xFFFF,
      adminFlags: 0,
      callFlags: 2 | 4 | 0x8000 | 0x10000 | 0x20000,
      videoResolution: 2
    };

    createdGroup.addMembers(selectedUsers, groupPermissions)
    if (groupPicture.url) {
      createdGroup.setImageUrl(groupPicture.url)
    }
  });
}
```

For example, I created a group called "ExampleGroup". On the console, `GroupListener listener` only prints once with group ID `124027`:
![image](https://user-images.githubusercontent.com/44438299/135213502-96887189-d9c1-4fb5-886d-6639a7453007.png)

But when I checked on Mesibo console, there are two groups with the same name with neighboring ID (`124028` and `124027`) but very distant Expiry Date. `124028` expires on Oct 17, 2021 07:18 PM while `124027` expires on Sep 28, 2024 01:18 PM as shown below.

![image](https://user-images.githubusercontent.com/44438299/135213921-bb6029fd-bf92-402b-95a3-baf5f4a53899.png)

On the other hand, when I called `getSortedProfile`, only one "ExampleGroup" with group ID `124027` appeared. I could not find group ID `124028`.

![image](https://user-images.githubusercontent.com/44438299/135214638-e316d1e2-10e9-4c7e-910c-673e6b2e9b85.png)

What do I need to do? And please let me know if you need more information. Thank you.

**Comment by mesibo** [comment]
You can give any name to the group, even the same name. The group ID will be different. 

It is like two different users of your app have created group "Family".

**Comment by vyonizr** [comment]
> 
> 
> You can give any name to the group, even the same name. The group ID will be different.
> 
> It is like two different users of your app have created groups name "Family".

The problem is it is "accidentally" created twice when `createdGroup` method is invoked and one of them is not found on `getSortedProfiles`.

**Comment by mesibo** [comment]
It is because it does not have members. `getSortedProfiles` will only return if the user is a member of that group. Also,  we are discouraging that method now. Please use `createGroup`

**Comment by vyonizr** [comment]
Is it possible to see whether `124028` and `124027` were created by the same user? And how do they have very distant Expiry Date while created almost at the same time?

**Comment by mesibo** [comment]
124028 was created by backend API - you have passed expiry here - please check your code before posting queries. Below is the parameter you have passed. 

>  op - groupadd , flag - 0 , name - Example Group , expiry - 31536000 , expiryext - 31536000 , active - 1 , token -  , 


124027 was created by some user, you must know which user. 

I am closing this.
