### ISSUE TITLE
Duplicate Question

### ISSUE THREAD

**Issue by NadeemHungryHop** [mesibo/samples#86]

**Comment by NadeemHungryHop** [comment]
@mesibo

**Comment by NadeemHungryHop** [comment]
reason: '-[__NSDictionaryM objectForKeyOrNil:]: unrecognized selector sent to instance 0x281926bc0'

@mesibo

**Comment by apathan12** [comment]
I am also receiving the same issue please check @mesibo

**Comment by NadeemHungryHop** [comment]
Duplicate
